name: keyboard_utils_example
description: Demonstrates how to use the keyboard_utils plugin.
publish_to: 'none'

version: 0.0.1+0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  keyboard_utils:
    path: ../

flutter:
  uses-material-design: true
